# Generated by Django 2.2.2 on 2019-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assettable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MODELNO', models.CharField(max_length=100)),
                ('MAKE', models.CharField(max_length=100)),
                ('PRODUCTNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cpufantable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dvdrwdrivetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='frontpanelswitchtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='graphicscardtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hddtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='keyboardtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mbdtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='memorytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='monitortable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mousetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='processortable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchasetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PURCHASENO', models.CharField(max_length=100)),
                ('ASSETID', models.CharField(max_length=100)),
                ('SERIALNO', models.CharField(max_length=100)),
                ('WARRANTY', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sascardtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='smpstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='systemfantable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AID', models.CharField(max_length=100)),
                ('SLNO', models.CharField(max_length=100)),
                ('CTNO', models.CharField(max_length=100)),
                ('SPNO', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=100)),
                ('USERNAME', models.CharField(max_length=100)),
                ('PASSWORD', models.CharField(max_length=100)),
                ('ROLE', models.CharField(max_length=100)),
            ],
        ),
    ]
