# Generated by Django 2.2.2 on 2019-06-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginwork', '0002_assettable_cpufantable_dvdrwdrivetable_frontpanelswitchtable_graphicscardtable_hddtable_keyboardtabl'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchaseassetmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PURCHASENO', models.CharField(max_length=100)),
                ('ASSETID', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='purchaserecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PURCHASENO', models.CharField(max_length=100)),
                ('SERIALNO', models.CharField(max_length=100)),
                ('WARRANTYSTARTDATE', models.CharField(max_length=100)),
                ('WARRANTYENDDATE', models.CharField(max_length=100)),
            ],
        ),
    ]
