# Generated by Django 2.2.2 on 2019-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginwork', '0004_auto_20190616_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessiontable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
