from django.db import models
 
# Create your models here.
#    def __str__(self):
#        return self.fname + ' ' + self.lname

class userstable(models.Model):
    #AUTOGENERATED ID
    name = models.CharField(max_length=100)
    employeeid = models.CharField(max_length=100) #(UNIQUE)
    email = models.CharField(max_length=100) #(UNIQUE)
    password = models.CharField(max_length=100) #(MD5 ENCRYPTION)
    role = models.CharField(max_length=100) #(ADMIN/USER)

class assetstable(models.Model):
    #AUTOGENERATED ASSET ID = models.CharField(max_length=100)
    modelno = models.CharField(max_length=100)
    make = models.CharField(max_length=100)
    productno = models.CharField(max_length=100)
    purchaseno = models.CharField(max_length=100)

class elementstable(models.Model):
    elementtype = models.CharField(max_length=100) #(HDD,MBD,SASCARD...) 
    assetid = models.CharField(max_length=100)
    slno = models.CharField(max_length=100)   #notnull
    ctno = models.CharField(max_length=100)
    spno = models.CharField(max_length=100)

class purchasestable(models.Model):
    purchaseno = models.CharField(max_length=100)
    serialno = models.CharField(max_length=100)
    warrantystartdate = models.CharField(max_length=100)
    warrantyenddate = models.CharField(max_length=100)

class sessiontable(models.Model):
    username = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    